### ISSUE TITLE
sg200x: trm: uart 中 表 21.43 中的 pin 信息和管脚复用部分信息重复

### ISSUE THREAD

**Issue by unicornx** [sophgo/sophgo-doc#116]
内容也不准确，建议删除

![image](https://github.com/sophgo/sophgo-doc/assets/2476165/6310df21-7147-40ad-a73a-e6b85f8d6696)

**Comment by unicornx** [comment]
@KennethLiu61 你觉得呢？要不要删掉算了？

**Comment by KennethLiu61** [comment]
嗯，的确这里的内容是不准确的。与pinout 的excel不吻合。可以删掉。
