### ISSUE TITLE
[SG200X] div_clk_187p5m, clk_187p5m registers missing, UART_SCLK configuration confusing

### ISSUE THREAD

**Issue by hellvesper** [sophgo/sophgo-doc#140]
There is a chapter about UART configuration in UART section page 555. UART_SCLK  configuration mention `div_clk_187p5m` register, which is missing in datasheet:
<img width="633" alt="image" src="https://github.com/user-attachments/assets/6466cead-730b-4548-a0a6-70924b409e52">
also there is mention about `clk_187p5m` register which description also missing:
<img width="668" alt="image" src="https://github.com/user-attachments/assets/90722ff1-cad7-4c67-82dc-b235fe201955">

Would be great to have an example for uart sclk configuration

**Comment by unicornx** [comment]
@KennethLiu61 hi, can you please double check this?

**Comment by KennethLiu61** [comment]
<img width="903" alt="image" src="https://github.com/user-attachments/assets/f1ead0b1-ae52-492f-adf6-6d2af9bcc355">
Sorry, there is an error in the document. This divider register should be div_clk_cam0_200.
