### ISSUE TITLE
【SG2002/TRM/cn】2.1 I2C interface number is wrong

### ISSUE THREAD

**Issue by lilysg200x** [sophgo/sophgo-doc#53]
the I2C number is 5
![image](https://github.com/sophgo/sophgo-doc/assets/151617306/92072223-24b2-45e5-a60e-1a60685a9743)

**Comment by unicornx** [comment]
重复了

**Comment by unicornx** [comment]
请关闭这个 issue，已经在 https://github.com/unicornx/sg200x-trm/issues/107 里解决了。谢谢
