### ISSUE TITLE
sg2042: Can not visit the provided website

### ISSUE THREAD

**Issue by Coekjan** [sophgo/sophgo-doc#55]
At least now, it seems that the link is invalid.

https://github.com/sophgo/sophgo-doc/blob/3df50a13e736a9dfec9b7baa4a02ea8dc069bd6e/SG2042/HowTo/A%20simple%20way%20to%20install%20ubuntu%20on%20SG2042%20EVB.rst?plain=1#L16

**Comment by Coekjan** [comment]
@SophgoChaoWei the provided link is still invalid, would you please help me download the image? Thanks.

**Comment by SophgoChaoWei** [comment]
Thanks your reply, we have fix this issue at pull request #88
