### ISSUE TITLE
sg200x: SPI description

### ISSUE THREAD

**Issue by roizano** [sophgo/sophgo-doc#77]
Hi,
I can't find in your data sheet if the SPI  can be full master or full slave.
Please advise

**Comment by unicornx** [comment]
Is this issue for sg2042 or sg200x, please title it, thanks.

**Comment by roizano** [comment]
On all respaberry pi models they declared that SPI can be only master

**Comment by unicornx** [comment]
For SG200x, SPI controller now only support working in master mode.
See https://github.com/sophgo/sophgo-doc/blob/main/SG200X/TRM/contents/en/peripherals/spi.rst
```rst
The system is configured with 4 SPI controller modules, which can be used as Master to conduct synchronous serial communication with external devices to achieve serial-to-parallel and parallel-to-serial conversion of data.
```

Any more quesiton, please let me know, otherwise I will close this issue.

**Comment by roizano** [comment]
Any future plans to have it as an receiver only slave?

**Comment by unicornx** [comment]
> Any future plans to have it as an receiver only slave?

Adding Liugui @KennethLiu61 to help answer this.

**Comment by KennethLiu61** [comment]
Based on IP datesheet, SPI can support slave mode. 
But we'll check internally to see if our designers customised this IP, and we'll also need to check if we support slave mode.

**Comment by unicornx** [comment]
@roizano  can we close this issue now?

**Comment by unicornx** [comment]
Close this issue due to no response for 2 month +.
