### ISSUE TITLE
sg2042: question about table 2 - Digital pin functions in chapter 3.1.2 Pin function

### ISSUE THREAD

**Issue by unicornx** [sophgo/sophgo-doc#78]
![image](https://github.com/sophgo/sophgo-doc/assets/2476165/69dc1ec8-4c38-4ea0-92fa-a80c545817eb)

What do the letters in “()” and “<>” mean?

For letters in "()", I guess "I" is "Input" and "O" is "Output". But I also saw a "D", what is it, see the picture below.
![image](https://github.com/sophgo/sophgo-doc/assets/2476165/0e74892c-4c20-4e35-92e8-c923927947e2)

For letters in "<>", I see "1" or "0", what does this mean? And some have "<>", some don't, why?

**Comment by SophgoChaoWei** [comment]
fixed #79
