### ISSUE TITLE
sg200x:trm: pwm description error

### ISSUE THREAD

**Issue by unicornx** [sophgo/sophgo-doc#99]
概述部分：

" 1 组 4 路" -> "4组，每组 4 路"

**Comment by KennethLiu61** [comment]
嗯，已跟内部owner确认，的确是4组，每组4路。文档之前没review到位。

**Comment by unicornx** [comment]
追加 issue #112

**Comment by unicornx** [comment]
merged into https://github.com/sophgo/sophgo-doc/issues/112

**Comment by unicornx** [comment]
closed
